modLoader="javafml"
loaderVersion="[4,)"
license="Apache License version 2.0"
issueTrackerURL="https://github.com/QuiteFrosty/Glacier-Gear/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://gigastudios.netlify.app/"
credits="created by gigastudios"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.137,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4,1.22)"
    ordering="AFTER"
    side="BOTH"
